<?xml version = "1.0" standalone = "no"?>
<!DOCTYPE teachers [
    <!ELEMENT teachers (teacher*)>
    <!ELEMENT teacher (name, course*)>
        <!ATTLIST teacher joiningDate CDATA #IMPLIED> 
        <!ATTLIST teacher jobRole CDATA #IMPLIED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT course (name, submodule*)>
    <!ELEMENT submodule (name, year+)>
    <!ELEMENT year (#PCDATA)>
]>
<teachers>
    <teacher joiningDate="2018" jobRole="Professor">
        <name>Alexandra Cristea</name>
        <course> 
            <name>Software, Systems and Applications III</name>
            <submodule> 
                <name>Advanced Databases</name>
                <year>2018-2019</year>
                <year>2019-2020</year>
            </submodule>
        </course>
        <course>
            <name>Software, Systems and Applications IV</name>
            <submodule>
                <name>Semantic Web</name>
                <year>2018-2019</year>
                <year>2019-2020</year>
            </submodule>
        </course>
    </teacher>
</teachers>
